!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure_priority: true
  backlight_compensation: 128
  brightness: 0
  contrast: 50
  enable_auto_exposure: true
  enable_auto_white_balance: false
  exposure: 166
  frames_queue_size: 16
  gain: 256
  global_time_enabled: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure_priority: true
      backlight_compensation: 128
      brightness: 0
      contrast: 50
      enable_auto_exposure: true
      enable_auto_white_balance: false
      exposure: 166
      frames_queue_size: 16
      gain: 256
      global_time_enabled: false
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      host_performance: 0
      hue: 2
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      power_line_frequency: 1
      saturation: 50
      sharpness: 50
      state: true
      type: ''
      white_balance: 5000.0
    state: []
  host_performance: 0
  hue: 2
  power_line_frequency: 1
  saturation: 50
  sharpness: 50
  white_balance: 5000.0
state: []
